// SPDX-FileCopyrightText: 2021 The Go Darwin Authors
// SPDX-License-Identifier: BSD-3-Clause

//go:build darwin && amd64 && gc
// +build darwin,amd64,gc

package sys

import (
	"unsafe"
)

//go:noescape
func crosscall2(fn, a unsafe.Pointer, n int32, ctxt uintptr)

// CrossCall2 called by C code generated by cmd/cgo.
// Saves C callee-saved registers and calls cgocallback with three arguments.
// fn is the PC of a func(a unsafe.Pointer) function.
func CrossCall2(fn, a unsafe.Pointer, n int32, ctxt uintptr) {
	crosscall2(fn, a, n, ctxt)
}
