// Copyright 2021 The Go Darwin Authors
// SPDX-License-Identifier: BSD-3-Clause

//go:build amd64 && gc
// +build amd64,gc

package sys

import (
	"unsafe"
)

//go:noescape
//go:nosplit
func _crosscall2(fn, a unsafe.Pointer, n int32, ctxt uintptr)

// CrossCall2 called by C code generated by cmd/cgo.
//
// Saves C callee-saved registers and calls cgocallback with three arguments.
// fn is the PC of a func(a unsafe.Pointer) function.
//
//go:nosplit
func CrossCall2(fn, a unsafe.Pointer, n int32, ctxt uintptr) {
	_crosscall2(fn, a, n, ctxt)
}
